In [18]:
import scipy
from scipy.linalg import qr
import numpy as np
import pprint

B = np.array([[2, -2], [4, 3], [1, -1]])
Q, R = qr(B)

print("B:")
pprint.pprint(B)

print ("Q:")
pprint.pprint(Q)

print ("R:")
pprint.pprint(R)

print("\n------------\n")
print("Problem 1 Verification")
A = np.array([[3,1,2], [-2,0,3], [0,-2,1]])
Q, R = qr(A)
print("A:")
pprint.pprint(A)

print ("Q:")
pprint.pprint(Q)

print ("R:")
pprint.pprint(R)

y = np.array([[5],[4],[0]])
print("\ny: \n",y)
Qty = np.matmul(Q.transpose(),y)
print("\nQ transpose * y:\n",Qty)

x_un = np.zeros(3)

#Back-Subtitution
n=3 #Dimension 3
for i in range(n-1, -1, -1):
    temp = Qty[i]
    for j in range(n-1, i, -1):
        temp = temp - x_un[j]*R[i,j]
        
    x_un[i] = temp/R[i,i]

print("\nSolution: ",x_un)

B:
array([[ 2, -2],
       [ 4,  3],
       [ 1, -1]])
Q:
array([[-4.36435780e-01,  7.80720058e-01, -4.47213595e-01],
       [-8.72871561e-01, -4.87950036e-01, -4.95102588e-18],
       [-2.18217890e-01,  3.90360029e-01,  8.94427191e-01]])
R:
array([[-4.58257569, -1.52752523],
       [ 0.        , -3.41565026],
       [ 0.        ,  0.        ]])

------------

Problem 1 Verification
B:
array([[ 3,  1,  2],
       [-2,  0,  3],
       [ 0, -2,  1]])
Q:
array([[-0.83205029, -0.14824986,  0.53452248],
       [ 0.5547002 , -0.22237479,  0.80178373],
       [-0.        ,  0.96362411,  0.26726124]])
R:
array([[-3.60555128e+00, -8.32050294e-01,  0.00000000e+00],
       [ 0.00000000e+00, -2.07549809e+00,  8.88178420e-16],
       [ 0.00000000e+00,  0.00000000e+00,  3.74165739e+00]])

y: 
 [[5]
 [4]
 [0]]

Q transpose * y:
 [[-1.94145069]
 [-1.6307485 ]
 [ 5.87974732]]

Solution:  [0.35714286 0.78571429 1.57142857]
